### PR TITLE
Added tar for drone build.

### PR DESCRIPTION
**Pull request by danharvey**

### CODE REVIEW

**Comment by vaijab** [comment]
The question is should we be using this image as drone base build image?

**Comment by danharvey** [comment]
No idea, but that's it's only purpose.

**Comment by vaijab** [comment]
> but that's it's only purpose.

I thought this image is used to build application images on top? And building them does not require tar neither sudo afaik.

**Comment by danharvey** [comment]
the JRE is used as image base, JDK is used to maven build then docker build. It's the docker version downloading that requires sudo and tar.

**Comment by vaijab** [comment]
Ah. Sorry for the confusion.

**Pull request merged**
